// Centralized API client: wraps all Wails backend bindings with
// explicit read retry policy and friendly error messages. Pages import
// from here instead of raw Wails bindings.
//
// Usage:
//   import { api } from "../api/client";
//   const plans = await api.governance.listAll();
//   // errors are already ApiError with friendly messages
//   } catch (e) { setError((e as Error).message); }

import {
  ApprovePlans,
  ApprovePurgePlan,
  ApproveRestorePlan,
  BuildDraftPlans,
  CancelScan,
  CheckRecoveryLock,
  CloseProject,
  CreateProjectFromSource,
  CreatePurgePlans,
  CreateRestorePlan,
  DiagnoseFormats,
  DiagnoseGovernance,
  DiagnoseMerges,
  ExecutePlans,
  ExecutePurge,
  ExecuteRestore,
  GetAppCapabilities,
  GetGroupDecision,
  GetGroupDetail,
  GetJobDetail,
  GetProjectInfo,
  GetProjectReadiness,
  GetScanCheckpoint,
  GetScanProgress,
  GetVersion,
  ListAllPlans,
  ListDuplicateGroups,
  ListGroupDecisions,
  ListJournalEntries,
  ListOperationLogs,
  ListPurgePlans,
  ListQuarantineItems,
  ListRecentJobs,
  ListRecentProjects,
  ListRestorePlans,
  ListReviewPlans,
  ListStorages,
  OpenProject,
  OpenProjectReadWrite,
  PickDirectory,
  RecoverPurges,
  RecoverRestores,
  RecoverSourcePlans,
  RegisterScanSource,
  SaveDraftPlans,
  SaveGroupDecision,
  StartScan,
  ValidateProjectPath,
} from "../wailsjs/go/wails/API";
import { wails, formatdiag, governancediag, merge } from "../wailsjs/go/models";
import { callOnce, callRead } from "./transport";

export { ApiError } from "./transport";

// ---- API client ----

export const api = {
  // ---- Project lifecycle ----
  project: {
    open: (path: string): Promise<wails.ProjectInfo> =>
      callOnce(() => OpenProject(path)),
    openReadWrite: (path: string): Promise<wails.ProjectInfo> =>
      callOnce(() => OpenProjectReadWrite(path)),
    close: (): Promise<void> =>
      callOnce(() => CloseProject()),
    info: (): Promise<wails.ProjectInfo> =>
      callRead(() => GetProjectInfo()),
    validatePath: (path: string): Promise<void> =>
      callRead(() => ValidateProjectPath(path)),
    version: (): Promise<wails.VersionInfo> =>
      callRead(() => GetVersion()),
    // V9 first-launch: CreateProjectFromSource atomically validates the
    // scan source, creates the project DB under the OS app-support dir,
    // registers the source as a storage (backend-generated ID), writes
    // project.json, and records the recent entry — all in one call with
    // rollback on failure. pickDirectory opens the native dialog (scan
    // source stays read-only, never written into). registerScanSource
    // adds an additional source to an open project (ID generated by
    // backend). listRecent returns recent projects for the start card.
    createFromSource: (input: wails.CreateProjectInput): Promise<wails.ProjectInfo> =>
      callOnce(() => CreateProjectFromSource(input)),
    pickDirectory: (title: string): Promise<string> =>
      callOnce(() => PickDirectory(title)),
    registerScanSource: (root: string): Promise<wails.StorageInfo> =>
      callOnce(() => RegisterScanSource(root)),
    listRecent: (): Promise<wails.RecentProjectEntry[]> =>
      callRead(() => ListRecentProjects()),
  },

  // ---- Scan operations ----
  scan: {
    start: (req: wails.StartScanRequest): Promise<wails.StartScanResponse> =>
      callOnce(() => StartScan(req)),
    cancel: (jobId: string): Promise<void> =>
      callOnce(() => CancelScan(jobId)),
    /** No retry — polling callers manage their own retry. */
    getProgress: (jobId: string): Promise<wails.ScanJobProgress> =>
      callOnce(() => GetScanProgress(jobId)),
    /** Check if a resumable checkpoint exists for the given root. */
    getCheckpoint: (root: string): Promise<wails.ScanCheckpointDTO> =>
      callRead(() => GetScanCheckpoint(root)),
    listJobs: (limit: number): Promise<wails.JobSummary[]> =>
      callRead(() => ListRecentJobs(limit)),
    getJobDetail: (jobId: string): Promise<wails.JobDetailResponse> =>
      callRead(() => GetJobDetail(jobId)),
  },

  // ---- Storage ----
  storages: {
    list: (): Promise<wails.StorageInfo[]> =>
      callRead(() => ListStorages()),
  },

  // ---- Duplicate results ----
  duplicates: {
    listGroups: (req: wails.ListGroupsRequest): Promise<wails.ListGroupsResponse> =>
      callRead(() => ListDuplicateGroups(req)),
    getDetail: (storageId: string, sha256: string): Promise<wails.GroupDetailResponse> =>
      callRead(() => GetGroupDetail(storageId, sha256)),
  },

  // ---- Governance review ----
  governance: {
    buildDrafts: (storageId: string): Promise<wails.PlanDTO[]> =>
      callRead(() => BuildDraftPlans(storageId)),
    saveDrafts: (storageId: string): Promise<wails.PlanDTO[]> =>
      callOnce(() => SaveDraftPlans(storageId)),
    listAll: (): Promise<wails.PlanDTO[]> =>
      callRead(() => ListAllPlans()),
    listReview: (): Promise<wails.PlanDTO[]> =>
      callRead(() => ListReviewPlans()),
    approve: (req: wails.ApprovePlansRequest): Promise<wails.ApprovePlansResponse> =>
      callOnce(() => ApprovePlans(req)),
    listDecisions: (groupId: string): Promise<wails.GroupDecisionDTO[]> =>
      callRead(() => ListGroupDecisions(groupId)),
    getDecision: (groupId: string): Promise<wails.GroupDecisionDTO> =>
      callRead(() => GetGroupDecision(groupId)),
    saveDecision: (req: wails.SaveDecisionRequest): Promise<wails.GroupDecisionDTO> =>
      callOnce(() => SaveGroupDecision(req)),
  },

  // ---- Execution center ----
  execution: {
    executePlans: (req: wails.ExecutePlansRequest): Promise<wails.ExecutePlansResponse> =>
      callOnce(() => ExecutePlans(req)),
    listQuarantine: (statusFilter: string): Promise<wails.QuarantineItemDTO[]> =>
      callRead(() => ListQuarantineItems(statusFilter)),
    createRestorePlan: (itemId: string): Promise<wails.RestorePlanDTO> =>
      callOnce(() => CreateRestorePlan(itemId)),
    approveRestore: (planId: string, digest: string): Promise<void> =>
      callOnce(() => ApproveRestorePlan(planId, digest)),
    executeRestore: (req: wails.ExecuteRestoreRequest): Promise<wails.ExecuteRestoreResponse> =>
      callOnce(() => ExecuteRestore(req)),
    listRestores: (): Promise<wails.RestorePlanDTO[]> =>
      callRead(() => ListRestorePlans()),
    createPurgePlans: (): Promise<wails.PurgePlanDTO[]> =>
      callOnce(() => CreatePurgePlans()),
    approvePurge: (planId: string, digest: string): Promise<void> =>
      callOnce(() => ApprovePurgePlan(planId, digest)),
    executePurge: (req: wails.ExecutePurgeRequest): Promise<wails.ExecutePurgeResponse> =>
      callOnce(() => ExecutePurge(req)),
    listPurges: (): Promise<wails.PurgePlanDTO[]> =>
      callRead(() => ListPurgePlans()),
  },

  // ---- Recovery ----
  recovery: {
    /** No retry — polled frequently, caller manages retry. */
    checkLock: (): Promise<wails.RecoveryStatusDTO> =>
      callOnce(() => CheckRecoveryLock()),
    recoverSource: (): Promise<wails.RecoveryResultDTO[]> =>
      callOnce(() => RecoverSourcePlans()),
    recoverRestores: (req: wails.RecoverRestoresRequest): Promise<wails.RestoreRecoveryResultDTO[]> =>
      callOnce(() => RecoverRestores(req)),
    recoverPurges: (quarantineRoot: string): Promise<wails.PurgeRecoveryResultDTO[]> =>
      callOnce(() => RecoverPurges(quarantineRoot)),
  },

  // ---- Audit ----
  audit: {
    listLogs: (planFilter: string): Promise<wails.OperationLogDTO[]> =>
      callRead(() => ListOperationLogs(planFilter)),
    listJournal: (planFilter: string): Promise<wails.JournalEntryDTO[]> =>
      callRead(() => ListJournalEntries(planFilter)),
  },

  // ---- Diagnostics ----
  diagnostics: {
    formats: (req: wails.DiagnoseFormatsRequest): Promise<formatdiag.Report> =>
      callRead(() => DiagnoseFormats(req)),
    governance: (req: wails.DiagnoseGovernanceRequest): Promise<governancediag.Report> =>
      callRead(() => DiagnoseGovernance(req)),
    merges: (req: wails.DiagnoseMergesRequest): Promise<merge.DiagnosticReport> =>
      callRead(() => DiagnoseMerges(req)),
  },

  // ---- Capabilities & readiness ----
  capabilities: {
    get: (): Promise<wails.AppCapabilitiesDTO> =>
      callRead(() => GetAppCapabilities()),
    readiness: (): Promise<wails.ProjectReadinessDTO> =>
      callRead(() => GetProjectReadiness()),
  },
} as const;

// ---- Type re-exports for convenience ----

export type { wails, formatdiag, governancediag, merge };
