#!/usr/bin/env bash
# check-version-consistency.sh — Verify that all version sources agree
# with the VERSION file and BUNDLE_BUILD_NUMBER file, and that macOS
# Bundle version fields follow Apple's numeric-only requirement.
#
# Usage:
#   ./scripts/release/check-version-consistency.sh
#   ./scripts/release/check-version-consistency.sh --allow-untagged
#
# Without --allow-untagged, the script also verifies that the current
# Git tag (minus the leading 'v') matches VERSION. This is required for
# release builds. Development builds should use --allow-untagged.
#
# Info.plist is mandatory and always checked.
# Info.dev.plist is gitignored (generated by `wails dev`); if present
# it is checked, if absent it is skipped.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
VERSION_FILE="$ROOT/VERSION"
BUILD_NUMBER_FILE="$ROOT/BUNDLE_BUILD_NUMBER"
ALLOW_UNTAGGED=false

for arg in "$@"; do
    case "$arg" in
        --allow-untagged) ALLOW_UNTAGGED=true ;;
        *) echo "check-version: unknown argument '$arg'" >&2; exit 1 ;;
    esac
done

if [[ ! -f "$VERSION_FILE" ]]; then
    echo "check-version: VERSION file not found at $VERSION_FILE" >&2
    exit 1
fi

if [[ ! -f "$BUILD_NUMBER_FILE" ]]; then
    echo "check-version: BUNDLE_BUILD_NUMBER file not found at $BUILD_NUMBER_FILE" >&2
    exit 1
fi

VERSION="$(tr -d '[:space:]' < "$VERSION_FILE")"
BUILD_NUMBER="$(tr -d '[:space:]' < "$BUILD_NUMBER_FILE")"

# Validate SemVer format
if ! echo "$VERSION" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+(-(alpha|beta|rc)\.[0-9]+)?$'; then
    echo "check-version: FAIL — VERSION '$VERSION' is not valid SemVer" >&2
    exit 1
fi

# Validate BUNDLE_BUILD_NUMBER: must be a positive integer
if ! echo "$BUILD_NUMBER" | grep -qE '^[0-9]+$'; then
    echo "check-version: FAIL — BUNDLE_BUILD_NUMBER '$BUILD_NUMBER' is not a positive integer" >&2
    exit 1
fi

echo "check-version: VERSION = $VERSION"
echo "check-version: BUNDLE_BUILD_NUMBER = $BUILD_NUMBER"

ERRORS=0
fail() {
    echo "check-version: FAIL — $1" >&2
    ERRORS=$((ERRORS + 1))
}

# --- Check wails.json ---
WAILS_JSON="$ROOT/cmd/ndg-desktop/wails.json"
WAILS_VERSION="$(python3 -c "import json; print(json.load(open('$WAILS_JSON'))['info']['productVersion'])" 2>/dev/null || echo "")"
if [[ "$WAILS_VERSION" != "$VERSION" ]]; then
    fail "wails.json productVersion='$WAILS_VERSION', expected '$VERSION'"
else
    echo "check-version: OK — wails.json productVersion = $WAILS_VERSION"
fi

# --- Check package.json ---
PKG_JSON="$ROOT/cmd/ndg-desktop/frontend/package.json"
PKG_VERSION="$(python3 -c "import json; print(json.load(open('$PKG_JSON'))['version'])" 2>/dev/null || echo "")"
if [[ "$PKG_VERSION" != "$VERSION" ]]; then
    fail "package.json version='$PKG_VERSION', expected '$VERSION'"
else
    echo "check-version: OK — package.json version = $PKG_VERSION"
fi

# --- Check package-lock.json ---
LOCK_JSON="$ROOT/cmd/ndg-desktop/frontend/package-lock.json"
LOCK_VERSION="$(python3 -c "import json; print(json.load(open('$LOCK_JSON'))['version'])" 2>/dev/null || echo "")"
if [[ "$LOCK_VERSION" != "$VERSION" ]]; then
    fail "package-lock.json version='$LOCK_VERSION', expected '$VERSION'"
else
    echo "check-version: OK — package-lock.json version = $LOCK_VERSION"
fi

LOCK_PKG_VERSION="$(python3 -c "import json; print(json.load(open('$LOCK_JSON'))['packages']['']['version'])" 2>/dev/null || echo "")"
if [[ "$LOCK_PKG_VERSION" != "$VERSION" ]]; then
    fail "package-lock.json packages[''].version='$LOCK_PKG_VERSION', expected '$VERSION'"
else
    echo "check-version: OK — package-lock.json packages[''].version = $LOCK_PKG_VERSION"
fi

# --- Check macOS Bundle version fields ---
# CFBundleShortVersionString must be numeric-only (major.minor.patch)
SHORT_VERSION_EXPECTED="${VERSION%%-*}"

# CFBundleVersion must match BUNDLE_BUILD_NUMBER (monotonically increasing)
BUILD_NUMBER_EXPECTED="$BUILD_NUMBER"

check_plist() {
    local plist="$1"
    local required="$2"
    local label
    label="$(basename "$plist")"

    if [[ ! -f "$plist" ]]; then
        if [[ "$required" == "true" ]]; then
            fail "$label not found"
        else
            echo "check-version: SKIP — $label not found (optional, gitignored)"
        fi
        return
    fi

    local short_actual build_actual
    short_actual="$(grep -A1 'CFBundleShortVersionString' "$plist" | grep '<string>' | sed 's/.*<string>\([^<]*\)<\/string>.*/\1/' | tr -d '[:space:]')"
    build_actual="$(grep -A1 '<key>CFBundleVersion</key>' "$plist" | grep '<string>' | sed 's/.*<string>\([^<]*\)<\/string>.*/\1/' | tr -d '[:space:]')"

    if [[ "$short_actual" != "$SHORT_VERSION_EXPECTED" ]]; then
        fail "$label CFBundleShortVersionString='$short_actual', expected '$SHORT_VERSION_EXPECTED'"
    else
        echo "check-version: OK — $label CFBundleShortVersionString = $short_actual"
    fi

    if [[ "$build_actual" != "$BUILD_NUMBER_EXPECTED" ]]; then
        fail "$label CFBundleVersion='$build_actual', expected '$BUILD_NUMBER_EXPECTED'"
    else
        echo "check-version: OK — $label CFBundleVersion = $build_actual"
    fi

    # Verify CFBundleShortVersionString is numeric-only
    if ! echo "$short_actual" | grep -qE '^[0-9]+\.[0-9]+\.[0-9]+$'; then
        fail "$label CFBundleShortVersionString='$short_actual' contains non-numeric characters (Apple requires digits and periods only)"
    fi

    # Verify CFBundleVersion is a single positive integer
    if ! echo "$build_actual" | grep -qE '^[0-9]+$'; then
        fail "$label CFBundleVersion='$build_actual' is not a positive integer (Apple requires digits only)"
    fi
}

# Info.plist is tracked and mandatory.
check_plist "$ROOT/cmd/ndg-desktop/build/darwin/Info.plist" true

# Info.dev.plist is gitignored (generated by `wails dev`); check if present.
check_plist "$ROOT/cmd/ndg-desktop/build/darwin/Info.dev.plist" false

# --- Check Git tag (unless --allow-untagged) ---
if [[ "$ALLOW_UNTAGGED" == "false" ]]; then
    GIT_TAG="$(git describe --tags --exact-match 2>/dev/null || echo "")"
    if [[ -z "$GIT_TAG" ]]; then
        fail "no Git tag matches HEAD (use --allow-untagged for development builds)"
    elif [[ "${GIT_TAG#v}" != "$VERSION" ]]; then
        fail "Git tag '$GIT_TAG' does not match VERSION '$VERSION' (expected 'v$VERSION')"
    else
        echo "check-version: OK — Git tag = $GIT_TAG"
    fi
else
    echo "check-version: SKIP — Git tag check disabled (--allow-untagged)"
fi

# --- Summary ---
if [[ $ERRORS -gt 0 ]]; then
    echo "check-version: $ERRORS error(s) found" >&2
    exit 1
fi

echo "check-version: all checks passed"
