// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CloseProject() {
  return window['go']['wails']['API']['CloseProject']();
}

export function GetProjectInfo() {
  return window['go']['wails']['API']['GetProjectInfo']();
}

export function GetVersion() {
  return window['go']['wails']['API']['GetVersion']();
}

export function OpenProject(arg1) {
  return window['go']['wails']['API']['OpenProject'](arg1);
}

export function ValidateProjectPath(arg1) {
  return window['go']['wails']['API']['ValidateProjectPath'](arg1);
}
