// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApprovePlans(arg1) {
  return window['go']['wails']['API']['ApprovePlans'](arg1);
}

export function ApprovePurgePlan(arg1, arg2) {
  return window['go']['wails']['API']['ApprovePurgePlan'](arg1, arg2);
}

export function ApproveRestorePlan(arg1, arg2) {
  return window['go']['wails']['API']['ApproveRestorePlan'](arg1, arg2);
}

export function BuildDraftPlans(arg1) {
  return window['go']['wails']['API']['BuildDraftPlans'](arg1);
}

export function CancelScan(arg1) {
  return window['go']['wails']['API']['CancelScan'](arg1);
}

export function CheckRecoveryLock() {
  return window['go']['wails']['API']['CheckRecoveryLock']();
}

export function CloseProject() {
  return window['go']['wails']['API']['CloseProject']();
}

export function CreatePurgePlans() {
  return window['go']['wails']['API']['CreatePurgePlans']();
}

export function CreateRestorePlan(arg1) {
  return window['go']['wails']['API']['CreateRestorePlan'](arg1);
}

export function DiagnoseFormats(arg1) {
  return window['go']['wails']['API']['DiagnoseFormats'](arg1);
}

export function DiagnoseGovernance(arg1) {
  return window['go']['wails']['API']['DiagnoseGovernance'](arg1);
}

export function DiagnoseMerges(arg1) {
  return window['go']['wails']['API']['DiagnoseMerges'](arg1);
}

export function ExecutePurge(arg1) {
  return window['go']['wails']['API']['ExecutePurge'](arg1);
}

export function ExecuteRestore(arg1) {
  return window['go']['wails']['API']['ExecuteRestore'](arg1);
}

export function GetGroupDecision(arg1) {
  return window['go']['wails']['API']['GetGroupDecision'](arg1);
}

export function GetGroupDetail(arg1, arg2) {
  return window['go']['wails']['API']['GetGroupDetail'](arg1, arg2);
}

export function GetJobDetail(arg1) {
  return window['go']['wails']['API']['GetJobDetail'](arg1);
}

export function GetProjectInfo() {
  return window['go']['wails']['API']['GetProjectInfo']();
}

export function GetScanProgress(arg1) {
  return window['go']['wails']['API']['GetScanProgress'](arg1);
}

export function GetVersion() {
  return window['go']['wails']['API']['GetVersion']();
}

export function ListAllPlans() {
  return window['go']['wails']['API']['ListAllPlans']();
}

export function ListDuplicateGroups(arg1) {
  return window['go']['wails']['API']['ListDuplicateGroups'](arg1);
}

export function ListGroupDecisions(arg1) {
  return window['go']['wails']['API']['ListGroupDecisions'](arg1);
}

export function ListJournalEntries(arg1) {
  return window['go']['wails']['API']['ListJournalEntries'](arg1);
}

export function ListOperationLogs(arg1) {
  return window['go']['wails']['API']['ListOperationLogs'](arg1);
}

export function ListPurgePlans() {
  return window['go']['wails']['API']['ListPurgePlans']();
}

export function ListQuarantineItems(arg1) {
  return window['go']['wails']['API']['ListQuarantineItems'](arg1);
}

export function ListRecentJobs(arg1) {
  return window['go']['wails']['API']['ListRecentJobs'](arg1);
}

export function ListRestorePlans() {
  return window['go']['wails']['API']['ListRestorePlans']();
}

export function ListReviewPlans() {
  return window['go']['wails']['API']['ListReviewPlans']();
}

export function ListStorages() {
  return window['go']['wails']['API']['ListStorages']();
}

export function OpenProject(arg1) {
  return window['go']['wails']['API']['OpenProject'](arg1);
}

export function OpenProjectReadWrite(arg1) {
  return window['go']['wails']['API']['OpenProjectReadWrite'](arg1);
}

export function RecoverPurges(arg1) {
  return window['go']['wails']['API']['RecoverPurges'](arg1);
}

export function RecoverRestores(arg1) {
  return window['go']['wails']['API']['RecoverRestores'](arg1);
}

export function RecoverSourcePlans() {
  return window['go']['wails']['API']['RecoverSourcePlans']();
}

export function SaveGroupDecision(arg1) {
  return window['go']['wails']['API']['SaveGroupDecision'](arg1);
}

export function StartScan(arg1) {
  return window['go']['wails']['API']['StartScan'](arg1);
}

export function ValidateProjectPath(arg1) {
  return window['go']['wails']['API']['ValidateProjectPath'](arg1);
}
