import { useEffect, useState } from "react";

// Wails generates Go bindings under ./wailsjs/. During pure Vite dev
// (without Wails runtime), the import may fail; guard with a try/catch.
let GetVersion: () => Promise<VersionInfo> | VersionInfo;
let OpenProject: (path: string) => Promise<ProjectInfo>;
let CloseProject: () => Promise<void>;
let GetProjectInfo: () => Promise<ProjectInfo>;

interface VersionInfo {
  version: string;
  commit: string;
  build_time: string;
}

interface ProjectInfo {
  path: string;
  is_open: boolean;
  storage_count: number;
}

try {
  // The wailsjs directory is generated by `wails dev` or `wails build`.
  const m = await import("./wailsjs/go/main/API");
  GetVersion = m.GetVersion;
  OpenProject = m.OpenProject;
  CloseProject = m.CloseProject;
  GetProjectInfo = m.GetProjectInfo;
} catch {
  // Fallback for pure Vite dev without Wails runtime.
  GetVersion = () => ({ version: "dev", commit: "n/a", build_time: "n/a" });
  OpenProject = async (_p: string) => {
    throw new Error("Wails runtime not available");
  };
  CloseProject = async () => {};
  GetProjectInfo = async () => {
    throw new Error("Wails runtime not available");
  };
}

export default function App() {
  const [version, setVersion] = useState<VersionInfo | null>(null);
  const [project, setProject] = useState<ProjectInfo | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const v = GetVersion();
    if (v instanceof Promise) {
      v.then(setVersion).catch(() => setVersion({ version: "dev", commit: "n/a", build_time: "n/a" }));
    } else {
      setVersion(v);
    }
  }, []);

  const handleRefreshProject = async () => {
    try {
      const info = await GetProjectInfo();
      setProject(info);
      setError(null);
    } catch (e) {
      setError(String(e));
    }
  };

  return (
    <div className="app">
      <header className="app-header">
        <h1>NDG 数据治理工作台</h1>
        {version && (
          <span className="version-badge">
            v{version.version} ({version.commit})
          </span>
        )}
      </header>

      <main className="app-main">
        <section className="card">
          <h2>项目</h2>
          {project ? (
            <div className="project-info">
              <p>
                <strong>数据库：</strong>
                {project.path}
              </p>
              <p>
                <strong>存储数量：</strong>
                {project.storage_count}
              </p>
              <button onClick={handleRefreshProject}>刷新</button>
            </div>
          ) : (
            <p className="muted">尚未打开项目</p>
          )}
          {error && <p className="error">{error}</p>}
        </section>

        <section className="card">
          <h2>扫描</h2>
          <p className="muted">扫描功能将在后续 PR 中实现</p>
        </section>

        <section className="card">
          <h2>重复组</h2>
          <p className="muted">重复文件检测将在后续 PR 中实现</p>
        </section>
      </main>

      <footer className="app-footer">
        <p>NDG — NAS Data Governance · 只读 Alpha</p>
      </footer>
    </div>
  );
}
